sudo: false
language: elixir
elixir:
  - 1.4.5
  - 1.5.3
otp_release:
  - 19.0
  - 20.0
cache:
  directories:
    - _build
    - deps
notifications:
  email:
    on_failure: always
    on_success: change
